name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Current run ID ${{ github.run_id }}: Dump Context"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Compile
        run: msbuild .\build\build.proj /t:GithubBuild /p:BuildNo=${{ github.run_number }}

      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          name: Setup
          path: .\dist\Setup*.exe
