name: Build and Test

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Current run ID ${{github.run_id}}: Dump Context"
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: |
          echo "Run ID: ${{github.run_id}}"
          echo ${env:GITHUB_CONTEXT}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Compile
        run: msbuild .\build\build.proj /t:GithubBuild /p:BuildNo=${{github.run_number}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Dist
          path: |
            ./dist/*
            !./dist/.keep
            
  test:
    needs: build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2016, windows-2019]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: Dist
          path: ./dist

      - name: Install AutoIt
        env:
          AUTOIT_INSTALL_DIR: 'D:\Autoit3'
        run: |
          choco install autoit --no-progress --yes --install-args="/D=${env:AUTOIT_INSTALL_DIR}"
          echo "${env:AUTOIT_INSTALL_DIR}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: "Test artifacts"
        timeout-minutes: 5
        run: msbuild .\build\integration-test.proj

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: TestLogs
          path: |
            ./test/log/*
            !./test/log/.keep

