name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Current run ID ${{github.run_id}}: Dump Context"
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: |
          echo "Run ID: ${{github.run_id}}"
          echo ${env:GITHUB_CONTEXT}
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Install AutoIt
        env:
          AUTOIT_INSTALL_DIR: "D:/Autoit3"
        run: |
          choco install autoit --no-progress --yes --install-args="/D=${env:AUTOIT_INSTALL_DIR}"
          echo "${env:AUTOIT_INSTALL_DIR}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
      - name: Compile
        run: msbuild .\build\build.proj /t:GithubBuild /p:BuildNo=${{github.run_number}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Dist
          path: |
            ./dist/*
            !./dist/.keep    
            
            
