# This is a basic workflow to help you get started with Actions

name: Release-Test

on:
  workflow_dispatch:

jobs:
  release-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: View context attributes
        uses: actions/github-script@0.9.0
        with:
          script: |
            console.log(context)
            
      - name: Get artifact download URL
        id: get-dist-artifact-url
        uses: actions/github-script@0.9.0
        env:
          MY_ARTIFACT_NAME: "Dist"
          MY_RUN_ID: "449167763"
        with:
          #result-encoding: string
          script: |
            // Get list of artifacts for given run 
            const opts = github.actions.listWorkflowRunArtifacts.endpoint.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: process.env.MY_RUN_ID
            })
            const artifacts = await github.paginate(opts)
            
            // Find artifact with desired name
            var distArtifact = null
            for(const artifact of artifacts) {
              if(artifact.name == process.env.MY_ARTIFACT_NAME) {
                distArtifact = artifact
              }
            }
            if (!distArtifact) {
              throw "Artifact not found"
            }
            console.log(distArtifact)
            return distArtifact
            
      - name: Download dist artifacts
        env:
          DOWNLOAD_URL: ${{fromJson(steps.get-dist-artifact-url.outputs.result).archive_download_url}} 
        run: |
          echo "Downloading $DOWNLOAD_URL"
          curl -L -o Dist.zip -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" $DOWNLOAD_URL
          echo "Unzipping"
          unzip Dist.zip
          ls -r

