# This is a basic workflow to help you get started with Actions

name: Release-Test

on:
  workflow_dispatch:

jobs:
  release-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: View context attributes
        uses: actions/github-script@0.9.0
        with:
          script: |
            console.log(context)
            
      - name: Download artifacts
        uses: actions/github-script@0.9.0
        with:
          script: |
            const opts = github.issues.listWorkflowRunArtifacts.endpoint.merge({
              'hhonisch",
              'winhelp-for-win10-text',
              run_id: '449167763'
            })
            const artifacts = await github.paginate(opts)
            
            for(const artifact of artifacts) {
              console.log(artifact)
            }
