# This is a basic workflow to help you get started with Actions

name: Release-Test

on:
  workflow_dispatch:

jobs:
  release-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: View context attributes
        uses: actions/github-script@0.9.0
        with:
          script: |
            console.log(context)
            
      - name: Get artifact download URL
        id: get-dist-artifact-url
        uses: actions/github-script@0.9.0
        with:
          result-encoding: string
          script: |
            // Get list of artifacts for given run 
            const opts = github.actions.listWorkflowRunArtifacts.endpoint.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: '449167763'
            })
            const artifacts = await github.paginate(opts)
            
            // Find artifact named "Dist"
            var distArtifact = null
            for(const artifact of artifacts) {
              if(artifact.name == "Dist") {
                distArtifact = artifact
              }
            }
            if (!distArtifact) {
              throw "Artifact not found"
            }
            return distArtifact.archive_download_url
            
      - name: Download artifact
        run: |
          echo "Result: ${steps.gget-dist-artifact-url.outputs.result}}"
